//! Human-readable report generation — HTML and Markdown from KnowledgeGraph.
//!
//! Produces self-contained HTML (dark theme, interactive dashboard) and clean
//! Markdown reports from a `KnowledgeGraph`.
//!
//! The `to_html` function now delegates to the interactive dashboard module
//! (`dashboard::generate`). The legacy static HTML renderer is preserved as
//! `to_html_static` for reference and backward compatibility.

use crate::types::{Complexity, EdgeType, GraphEdge, GraphNode, KnowledgeGraph};
use std::collections::{HashMap, HashSet};

// ── Public API ───────────────────────────────────────────────────────────────

/// Generate an interactive HTML dashboard from the knowledge graph.
///
/// Delegates to `dashboard::generate()` which produces a self-contained
/// HTML file with D3.js force-directed graph visualization, search,
/// layer filtering, tour navigation, and a node detail panel.
pub fn to_html(graph: &KnowledgeGraph) -> String {
    crate::dashboard::generate(graph)
}

/// Generate the legacy static HTML report (no JavaScript interactivity).
/// Preserved for backward compatibility and reference.
pub fn to_html_static(graph: &KnowledgeGraph) -> String {
    let mut out = String::new();
    html_header(&mut out, graph);
    html_section_overview(&mut out, graph);
    html_section_layers(&mut out, graph);
    html_section_file_inventory(&mut out, graph);
    html_section_imports(&mut out, graph);
    html_section_dependency_tree(&mut out, graph);
    html_section_tour(&mut out, graph);
    html_footer(&mut out);
    out
}

/// Generate a Markdown report.
pub fn to_markdown(graph: &KnowledgeGraph) -> String {
    let mut out = String::new();
    md_title(&mut out, graph);
    md_section_overview(&mut out, graph);
    md_section_layers(&mut out, graph);
    md_section_file_inventory(&mut out, graph);
    md_section_imports(&mut out, graph);
    md_section_dependency_tree(&mut out, graph);
    md_section_tour(&mut out, graph);
    out
}

// ═══════════════════════════════════════════════════════════════════════════════
// HTML helpers
// ═══════════════════════════════════════════════════════════════════════════════

fn esc(s: &str) -> String {
    s.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
}

fn html_header(out: &mut String, graph: &KnowledgeGraph) {
    let title = format!("{} 知识图谱分析报告", esc(&graph.project.name));
    out.push_str("<!DOCTYPE html>\n<html lang=\"zh-CN\">\n<head>\n");
    out.push_str("<meta charset=\"UTF-8\">\n");
    out.push_str("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
    out.push_str(&format!("<title>{}</title>\n", title));
    out.push_str("<style>\n");
    out.push_str(include_str!("./report.css"));
    out.push_str("</style>\n</head>\n<body>\n");
    out.push_str(&format!(
        "<header><h1>{}</h1><p class=\"subtitle\">Understand Anything — Knowledge Graph Report</p></header>\n<main>\n",
        title
    ));
}

fn html_footer(out: &mut String) {
    out.push_str("</main>\n<footer><p>Generated by Understand Anything Rust</p></footer>\n</body>\n</html>\n");
}

fn html_section_open(out: &mut String, id: &str, title: &str) {
    out.push_str(&format!("<section id=\"{}\"><h2>{}</h2>\n", id, esc(title)));
}

fn html_section_close(out: &mut String) {
    out.push_str("</section>\n");
}

fn html_node_ref(node: &GraphNode) -> String {
    if let Some(ref fp) = node.file_path {
        format!(
            "<a href=\"#node-{}\" class=\"node-ref\" title=\"{}\">{}</a>",
            esc(&node.id),
            esc(&node.summary),
            esc(fp)
        )
    } else {
        format!(
            "<span class=\"node-ref\" title=\"{}\">{}</span>",
            esc(&node.summary),
            esc(&node.name)
        )
    }
}

// ── 1. Overview ──────────────────────────────────────────────────────────────

fn html_section_overview(out: &mut String, graph: &KnowledgeGraph) {
    html_section_open(out, "overview", "项目概览");

    out.push_str("<div class=\"overview-grid\">\n");
    out.push_str(&format!(
        "<div class=\"ov-card\"><span class=\"ov-label\">项目名称</span><span class=\"ov-value\">{}</span></div>\n",
        esc(&graph.project.name)
    ));
    out.push_str(&format!(
        "<div class=\"ov-card\"><span class=\"ov-label\">编程语言</span><span class=\"ov-value\">{}</span></div>\n",
        esc(&graph.project.languages.join(", "))
    ));
    out.push_str(&format!(
        "<div class=\"ov-card\"><span class=\"ov-label\">复杂度</span><span class=\"ov-value complexity-{}\">{:?}</span></div>\n",
        format!("{:?}", complexity_of_graph(graph)).to_lowercase(),
        complexity_of_graph(graph)
    ));
    out.push_str(&format!(
        "<div class=\"ov-card\"><span class=\"ov-label\">分析时间</span><span class=\"ov-value\">{}</span></div>\n",
        esc(&graph.project.analyzed_at)
    ));
    if graph.project.git_commit_hash != "unknown" {
        out.push_str(&format!(
            "<div class=\"ov-card\"><span class=\"ov-label\">Git Commit</span><span class=\"ov-value mono\">{}</span></div>\n",
            esc(&graph.project.git_commit_hash)
        ));
    }
    out.push_str(&format!(
        "<div class=\"ov-card\"><span class=\"ov-label\">节点总数</span><span class=\"ov-value\">{}</span></div>\n",
        graph.nodes.len()
    ));
    out.push_str(&format!(
        "<div class=\"ov-card\"><span class=\"ov-label\">关系连线</span><span class=\"ov-value\">{}</span></div>\n",
        graph.edges.len()
    ));
    out.push_str(&format!(
        "<div class=\"ov-card\"><span class=\"ov-label\">架构层数</span><span class=\"ov-value\">{}</span></div>\n",
        graph.layers.len()
    ));
    out.push_str("</div>\n");

    out.push_str(&format!(
        "<p class=\"description\">{}</p>\n",
        esc(&graph.project.description)
    ));

    html_section_close(out);
}

// ── 2. Layers ────────────────────────────────────────────────────────────────

fn html_section_layers(out: &mut String, graph: &KnowledgeGraph) {
    html_section_open(out, "layers", "架构分层");

    let node_map: HashMap<&str, &GraphNode> =
        graph.nodes.iter().map(|n| (n.id.as_str(), n)).collect();

    // Color palette for layers
    let layer_colors = [
        ("code", "#4fc3f7", "#0288d1"),
        ("config", "#fff176", "#f9a825"),
        ("docs", "#a5d6a7", "#388e3c"),
        ("infra", "#ef9a9a", "#c62828"),
        ("data", "#ce93d8", "#7b1fa2"),
        ("api", "#ffcc80", "#e65100"),
        ("scripts", "#b0bec5", "#455a64"),
    ];

    for layer in &graph.layers {
        let (bg, border) = layer_colors
            .iter()
            .find(|(id, ..)| *id == layer.id)
            .map(|(_, bg, border)| (*bg, *border))
            .unwrap_or(("#424242", "#616161"));

        out.push_str(&format!(
            "<div class=\"layer-card\" style=\"border-left: 4px solid {}; background: linear-gradient(135deg, {}22 0%, {}08 100%);\">\n",
            border, bg, bg
        ));
        out.push_str(&format!(
            "<h3><span class=\"layer-dot\" style=\"background:{}\"></span>{} <span class=\"layer-count\">({} items)</span></h3>\n",
            border,
            esc(&layer.name),
            layer.node_ids.len()
        ));
        out.push_str(&format!(
            "<p class=\"layer-desc\">{}</p>\n",
            esc(&layer.description)
        ));

        if !layer.node_ids.is_empty() {
            out.push_str("<ul class=\"layer-nodes\">\n");
            for nid in &layer.node_ids {
                if let Some(node) = node_map.get(nid.as_str()) {
                    let label = node.file_path.as_deref().unwrap_or(&node.name);
                    out.push_str(&format!(
                        "<li id=\"node-{}\">{}</li>\n",
                        esc(&node.id),
                        esc(label)
                    ));
                }
            }
            out.push_str("</ul>\n");
        }
        out.push_str("</div>\n");
    }

    html_section_close(out);
}

// ── 3. File Inventory ────────────────────────────────────────────────────────

fn html_section_file_inventory(out: &mut String, graph: &KnowledgeGraph) {
    html_section_open(out, "files", "文件清单");

    let file_nodes: Vec<&GraphNode> = graph
        .nodes
        .iter()
        .filter(|n| n.file_path.is_some())
        .collect();

    out.push_str("<div class=\"table-wrap\"><table class=\"file-table\">\n");
    out.push_str(
        "<thead><tr><th>路径</th><th>语言</th><th>行数</th><th>类别</th></tr></thead>\n<tbody>\n",
    );

    for node in &file_nodes {
        let path = node.file_path.as_deref().unwrap_or("-");
        let language = node.tags.first().map(|s| s.as_str()).unwrap_or("-");

        // Extract line count from summary (e.g., "rust (150 lines, 2 definitions, 1 imports)")
        let lines = extract_line_count(&node.summary).unwrap_or("?");

        let category = format!("{:?}", node.node_type);

        out.push_str(&format!(
            "<tr><td class=\"path-col\">{}</td><td><span class=\"lang-badge\">{}</span></td><td class=\"num\">{}</td><td>{}</td></tr>\n",
            esc(path),
            esc(language),
            lines,
            esc(&category)
        ));
    }

    out.push_str("</tbody>\n</table></div>\n");
    html_section_close(out);
}

// ── 4. Import Relationships ──────────────────────────────────────────────────

fn html_section_imports(out: &mut String, graph: &KnowledgeGraph) {
    let import_edges: Vec<&GraphEdge> = graph
        .edges
        .iter()
        .filter(|e| e.edge_type == EdgeType::Imports)
        .collect();

    html_section_open(out, "imports", "导入关系");

    if import_edges.is_empty() {
        out.push_str("<p class=\"empty\">未检测到导入关系。</p>\n");
    } else {
        let node_map: HashMap<&str, &GraphNode> =
            graph.nodes.iter().map(|n| (n.id.as_str(), n)).collect();

        out.push_str(&format!("<p>共 {} 条导入关系：</p>\n", import_edges.len()));
        out.push_str("<ul class=\"import-list\">\n");

        for edge in &import_edges {
            let src_label = node_map
                .get(edge.source.as_str())
                .and_then(|n| n.file_path.as_deref())
                .unwrap_or(&edge.source);
            let tgt_label = node_map
                .get(edge.target.as_str())
                .and_then(|n| n.file_path.as_deref())
                .unwrap_or(&edge.target);

            out.push_str(&format!(
                "<li>{esc_src} → {esc_tgt}",
                esc_src = esc(src_label),
                esc_tgt = esc(tgt_label)
            ));
            if let Some(ref desc) = edge.description {
                out.push_str(&format!(
                    " <span class=\"edge-desc\">({})</span>",
                    esc(desc)
                ));
            }
            out.push_str("</li>\n");
        }
        out.push_str("</ul>\n");
    }

    html_section_close(out);
}

// ── 5. Dependency Tree ───────────────────────────────────────────────────────

fn html_section_dependency_tree(out: &mut String, graph: &KnowledgeGraph) {
    html_section_open(out, "tree", "目录结构");

    let node_map: HashMap<&str, &GraphNode> =
        graph.nodes.iter().map(|n| (n.id.as_str(), n)).collect();

    // Build a parent→children map from Contains edges
    let mut children: HashMap<&str, Vec<&str>> = HashMap::new();
    for edge in &graph.edges {
        if edge.edge_type == EdgeType::Contains {
            children.entry(&edge.source).or_default().push(&edge.target);
        }
    }

    // Find root nodes (no incoming Contains edge)
    let all_targets: HashSet<&str> = graph
        .edges
        .iter()
        .filter(|e| e.edge_type == EdgeType::Contains)
        .map(|e| e.target.as_str())
        .collect();
    let roots: Vec<&&str> = children
        .keys()
        .filter(|k| !all_targets.contains(**k))
        .collect();

    out.push_str("<pre class=\"ascii-tree\">\n");
    let mut seen = HashSet::new();
    for root in roots {
        if !seen.contains(&root.to_string()) {
            render_html_tree(out, root, &children, &node_map, "", true, &mut seen);
        }
    }
    out.push_str("</pre>\n");

    html_section_close(out);
}

fn render_html_tree(
    out: &mut String,
    node_id: &str,
    children: &HashMap<&str, Vec<&str>>,
    node_map: &HashMap<&str, &GraphNode>,
    prefix: &str,
    is_last: bool,
    seen: &mut HashSet<String>,
) {
    if !seen.insert(node_id.to_string()) {
        return;
    }
    let label = node_map
        .get(node_id)
        .and_then(|n| n.file_path.as_deref())
        .or_else(|| node_map.get(node_id).map(|n| n.name.as_str()))
        .unwrap_or(node_id);

    let connector = if prefix.is_empty() {
        ""
    } else if is_last {
        "└── "
    } else {
        "├── "
    };
    out.push_str(&format!("{}{}{}\n", esc(prefix), connector, esc(label)));

    if let Some(kids) = children.get(node_id) {
        let new_prefix = if prefix.is_empty() {
            "".to_string()
        } else if is_last {
            format!("{}    ", prefix)
        } else {
            format!("{}│   ", prefix)
        };
        for (i, kid) in kids.iter().enumerate() {
            let kid_is_last = i == kids.len() - 1;
            render_html_tree(out, kid, children, node_map, &new_prefix, kid_is_last, seen);
        }
    }
}

// ── 6. Guided Tour ───────────────────────────────────────────────────────────

fn html_section_tour(out: &mut String, graph: &KnowledgeGraph) {
    html_section_open(out, "tour", "引导之旅");

    let node_map: HashMap<&str, &GraphNode> =
        graph.nodes.iter().map(|n| (n.id.as_str(), n)).collect();

    for step in &graph.tour {
        out.push_str(&format!(
            "<div class=\"tour-step\">\n<h3><span class=\"step-num\">{}</span> {}</h3>\n",
            step.order,
            esc(&step.title)
        ));
        out.push_str(&format!("<p>{}</p>\n", esc(&step.description)));

        if let Some(ref lesson) = step.language_lesson {
            out.push_str(&format!(
                "<blockquote class=\"lesson\">💡 {}</blockquote>\n",
                esc(lesson)
            ));
        }

        if !step.node_ids.is_empty() {
            out.push_str("<ul class=\"tour-nodes\">\n");
            for nid in &step.node_ids {
                let label = node_map
                    .get(nid.as_str())
                    .and_then(|n| n.file_path.as_deref())
                    .unwrap_or(nid);
                out.push_str(&format!("<li>{}</li>\n", esc(label)));
            }
            out.push_str("</ul>\n");
        }
        out.push_str("</div>\n");
    }

    html_section_close(out);
}

// ═══════════════════════════════════════════════════════════════════════════════
// Markdown helpers
// ═══════════════════════════════════════════════════════════════════════════════

fn md_title(out: &mut String, graph: &KnowledgeGraph) {
    out.push_str(&format!("# {} 知识图谱分析报告\n\n", graph.project.name));
    out.push_str("> Generated by Understand Anything Rust\n\n");
    out.push_str("---\n\n");
}

// ── 1. Overview ──────────────────────────────────────────────────────────────

fn md_section_overview(out: &mut String, graph: &KnowledgeGraph) {
    out.push_str("## 项目概览\n\n");
    out.push_str("| 属性 | 值 |\n|------|----|\n");
    out.push_str(&format!("| 项目名称 | {} |\n", graph.project.name));
    out.push_str(&format!(
        "| 编程语言 | {} |\n",
        graph.project.languages.join(", ")
    ));
    out.push_str(&format!("| 复杂度 | {:?} |\n", complexity_of_graph(graph)));
    out.push_str(&format!("| 分析时间 | {} |\n", graph.project.analyzed_at));
    if graph.project.git_commit_hash != "unknown" {
        out.push_str(&format!(
            "| Git Commit | `{}` |\n",
            graph.project.git_commit_hash
        ));
    }
    out.push_str(&format!("| 节点总数 | {} |\n", graph.nodes.len()));
    out.push_str(&format!("| 关系连线 | {} |\n", graph.edges.len()));
    out.push_str(&format!("| 架构层数 | {} |\n", graph.layers.len()));
    out.push('\n');
    out.push_str(&format!("{}\n\n", graph.project.description));
    out.push_str("---\n\n");
}

// ── 2. Layers ────────────────────────────────────────────────────────────────

fn md_section_layers(out: &mut String, graph: &KnowledgeGraph) {
    out.push_str("## 架构分层\n\n");

    let node_map: HashMap<&str, &GraphNode> =
        graph.nodes.iter().map(|n| (n.id.as_str(), n)).collect();

    for layer in &graph.layers {
        out.push_str(&format!(
            "### {} ({})\n\n",
            layer.name,
            layer.node_ids.len()
        ));
        out.push_str(&format!("_{}_\n\n", layer.description));

        if !layer.node_ids.is_empty() {
            for nid in &layer.node_ids {
                if let Some(node) = node_map.get(nid.as_str()) {
                    let label = node.file_path.as_deref().unwrap_or(&node.name);
                    out.push_str(&format!("- `{}`\n", label));
                }
            }
            out.push('\n');
        }
    }

    out.push_str("---\n\n");
}

// ── 3. File Inventory ────────────────────────────────────────────────────────

fn md_section_file_inventory(out: &mut String, graph: &KnowledgeGraph) {
    out.push_str("## 文件清单\n\n");

    let file_nodes: Vec<&GraphNode> = graph
        .nodes
        .iter()
        .filter(|n| n.file_path.is_some())
        .collect();

    out.push_str("| 路径 | 语言 | 行数 | 类别 |\n");
    out.push_str("|------|------|------|------|\n");

    for node in &file_nodes {
        let path = node.file_path.as_deref().unwrap_or("-");
        let language = node.tags.first().map(|s| s.as_str()).unwrap_or("-");
        let lines = extract_line_count(&node.summary).unwrap_or("?");
        let category = format!("{:?}", node.node_type);

        out.push_str(&format!(
            "| `{}` | {} | {} | {} |\n",
            path, language, lines, category
        ));
    }

    out.push_str("\n---\n\n");
}

// ── 4. Import Relationships ──────────────────────────────────────────────────

fn md_section_imports(out: &mut String, graph: &KnowledgeGraph) {
    let import_edges: Vec<&GraphEdge> = graph
        .edges
        .iter()
        .filter(|e| e.edge_type == EdgeType::Imports)
        .collect();

    out.push_str("## 导入关系\n\n");

    if import_edges.is_empty() {
        out.push_str("*未检测到导入关系。*\n\n");
    } else {
        let node_map: HashMap<&str, &GraphNode> =
            graph.nodes.iter().map(|n| (n.id.as_str(), n)).collect();

        out.push_str(&format!("共 {} 条导入关系：\n\n", import_edges.len()));

        for edge in &import_edges {
            let src_label = node_map
                .get(edge.source.as_str())
                .and_then(|n| n.file_path.as_deref())
                .unwrap_or(&edge.source);
            let tgt_label = node_map
                .get(edge.target.as_str())
                .and_then(|n| n.file_path.as_deref())
                .unwrap_or(&edge.target);

            out.push_str(&format!("- `{}` → `{}`\n", src_label, tgt_label));
        }
        out.push('\n');
    }

    out.push_str("---\n\n");
}

// ── 5. Dependency Tree ───────────────────────────────────────────────────────

fn md_section_dependency_tree(out: &mut String, graph: &KnowledgeGraph) {
    out.push_str("## 目录结构\n\n");

    let node_map: HashMap<&str, &GraphNode> =
        graph.nodes.iter().map(|n| (n.id.as_str(), n)).collect();

    // Build parent→children from Contains edges
    let mut children: HashMap<&str, Vec<&str>> = HashMap::new();
    for edge in &graph.edges {
        if edge.edge_type == EdgeType::Contains {
            children.entry(&edge.source).or_default().push(&edge.target);
        }
    }

    let all_targets: HashSet<&str> = graph
        .edges
        .iter()
        .filter(|e| e.edge_type == EdgeType::Contains)
        .map(|e| e.target.as_str())
        .collect();
    let mut roots: Vec<&&str> = children
        .keys()
        .filter(|k| !all_targets.contains(**k))
        .collect();
    roots.sort();

    out.push_str("```\n");
    let mut seen = HashSet::new();
    for root in roots {
        if !seen.contains(*root) {
            render_md_tree(out, root, &children, &node_map, "", true, &mut seen);
        }
    }
    out.push_str("```\n\n");
    out.push_str("---\n\n");
}

fn render_md_tree(
    out: &mut String,
    node_id: &str,
    children: &HashMap<&str, Vec<&str>>,
    node_map: &HashMap<&str, &GraphNode>,
    prefix: &str,
    is_last: bool,
    seen: &mut HashSet<String>,
) {
    if !seen.insert(node_id.to_string()) {
        return;
    }
    let label = node_map
        .get(node_id)
        .and_then(|n| n.file_path.as_deref())
        .or_else(|| node_map.get(node_id).map(|n| n.name.as_str()))
        .unwrap_or(node_id);

    let connector = if prefix.is_empty() {
        ""
    } else if is_last {
        "└── "
    } else {
        "├── "
    };
    out.push_str(&format!("{}{}{}\n", prefix, connector, label));

    if let Some(kids) = children.get(node_id) {
        let new_prefix = if prefix.is_empty() {
            "".to_string()
        } else if is_last {
            format!("{}    ", prefix)
        } else {
            format!("{}│   ", prefix)
        };
        for (i, kid) in kids.iter().enumerate() {
            let kid_is_last = i == kids.len() - 1;
            render_md_tree(out, kid, children, node_map, &new_prefix, kid_is_last, seen);
        }
    }
}

// ── 6. Guided Tour ───────────────────────────────────────────────────────────

fn md_section_tour(out: &mut String, graph: &KnowledgeGraph) {
    out.push_str("## 引导之旅\n\n");

    let node_map: HashMap<&str, &GraphNode> =
        graph.nodes.iter().map(|n| (n.id.as_str(), n)).collect();

    for step in &graph.tour {
        out.push_str(&format!("### {}. {}\n\n", step.order, step.title));
        out.push_str(&format!("{}\n\n", step.description));

        if let Some(ref lesson) = step.language_lesson {
            out.push_str(&format!("> 💡 {}\n\n", lesson));
        }

        if !step.node_ids.is_empty() {
            for nid in &step.node_ids {
                let label = node_map
                    .get(nid.as_str())
                    .and_then(|n| n.file_path.as_deref())
                    .unwrap_or(nid);
                out.push_str(&format!("- `{}`\n", label));
            }
            out.push('\n');
        }
    }
}

// ═══════════════════════════════════════════════════════════════════════════════
// Shared helpers
// ═══════════════════════════════════════════════════════════════════════════════

/// Determine overall graph complexity from node complexities.
fn complexity_of_graph(graph: &KnowledgeGraph) -> Complexity {
    let mut counts = [0usize; 3]; // Simple, Moderate, Complex
    for node in &graph.nodes {
        match node.complexity {
            Complexity::Simple => counts[0] += 1,
            Complexity::Moderate => counts[1] += 1,
            Complexity::Complex => counts[2] += 1,
        }
    }
    if counts[2] > counts[0] + counts[1] {
        Complexity::Complex
    } else if counts[1] > counts[0] {
        Complexity::Moderate
    } else {
        Complexity::Simple
    }
}

/// Extract line count from summary string like "rust (150 lines, 2 definitions, 1 imports)".
fn extract_line_count(summary: &str) -> Option<&str> {
    let start = summary.find('(')?;
    let end = summary[start..].find(" lines")?;
    Some(&summary[start + 1..start + end])
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::types::{
        Direction, FileCategory, GraphEdge, GraphNode, Layer, NodeType, ProjectMeta, TourStep,
    };

    fn make_test_graph() -> KnowledgeGraph {
        KnowledgeGraph {
            version: "1.0.0".into(),
            kind: Some("codebase".into()),
            project: ProjectMeta {
                name: "test-project".into(),
                languages: vec!["rust".into(), "python".into()],
                frameworks: vec![],
                description: "A test project for report generation.".into(),
                analyzed_at: "2025-01-15T10:30:00Z".into(),
                git_commit_hash: "abc123def456".into(),
            },
            nodes: vec![
                GraphNode {
                    id: "n1".into(),
                    node_type: NodeType::File,
                    name: "main".into(),
                    file_path: Some("src/main.rs".into()),
                    line_range: None,
                    summary: "rust (150 lines, 2 definitions, 1 imports)".into(),
                    tags: vec!["rust".into()],
                    complexity: Complexity::Moderate,
                    language_notes: None,
                    domain_meta: None,
                    knowledge_meta: None,
                },
                GraphNode {
                    id: "n2".into(),
                    node_type: NodeType::File,
                    name: "lib".into(),
                    file_path: Some("src/lib.rs".into()),
                    line_range: None,
                    summary: "rust (50 lines)".into(),
                    tags: vec!["rust".into()],
                    complexity: Complexity::Simple,
                    language_notes: None,
                    domain_meta: None,
                    knowledge_meta: None,
                },
                GraphNode {
                    id: "n3".into(),
                    node_type: NodeType::Config,
                    name: "Cargo".into(),
                    file_path: Some("Cargo.toml".into()),
                    line_range: None,
                    summary: "toml (20 lines)".into(),
                    tags: vec!["toml".into()],
                    complexity: Complexity::Simple,
                    language_notes: None,
                    domain_meta: None,
                    knowledge_meta: None,
                },
                GraphNode {
                    id: "n4".into(),
                    node_type: NodeType::Module,
                    name: "src".into(),
                    file_path: None,
                    line_range: None,
                    summary: "Directory: src".into(),
                    tags: vec!["directory".into()],
                    complexity: Complexity::Simple,
                    language_notes: None,
                    domain_meta: None,
                    knowledge_meta: None,
                },
            ],
            edges: vec![
                GraphEdge {
                    source: "n4".into(),
                    target: "n1".into(),
                    edge_type: EdgeType::Contains,
                    direction: Direction::Forward,
                    description: Some("src contains src/main.rs".into()),
                    weight: 0.3,
                },
                GraphEdge {
                    source: "n4".into(),
                    target: "n2".into(),
                    edge_type: EdgeType::Contains,
                    direction: Direction::Forward,
                    description: Some("src contains src/lib.rs".into()),
                    weight: 0.3,
                },
                GraphEdge {
                    source: "n1".into(),
                    target: "n2".into(),
                    edge_type: EdgeType::Imports,
                    direction: Direction::Forward,
                    description: Some("main imports lib".into()),
                    weight: 0.5,
                },
            ],
            layers: vec![
                Layer {
                    id: "code".into(),
                    name: "Core Code".into(),
                    description: "Source code files".into(),
                    node_ids: vec!["n1".into(), "n2".into()],
                },
                Layer {
                    id: "config".into(),
                    name: "Configuration".into(),
                    description: "Config files".into(),
                    node_ids: vec!["n3".into()],
                },
            ],
            tour: vec![TourStep {
                order: 1,
                title: "Project Overview".into(),
                description: "This is a test project.".into(),
                node_ids: vec!["n1".into(), "n2".into()],
                language_lesson: Some("Knowledge graphs represent code as nodes.".into()),
            }],
        }
    }

    #[test]
    fn test_to_html_contains_sections() {
        let graph = make_test_graph();
        let html = to_html(&graph);
        assert!(html.contains("<!DOCTYPE html>"));
        assert!(html.contains("test-project"));
        assert!(html.contains("GRAPH_DATA"));
        assert!(html.contains("graph-svg"));
        assert!(html.contains("search-input"));
        assert!(html.contains("detail-panel"));
        assert!(html.contains("stats-bar"));
        // Verify escape works
        assert!(!html.contains("<script>alert"));
    }

    #[test]
    fn test_to_html_static_legacy() {
        let graph = make_test_graph();
        let html = to_html_static(&graph);
        assert!(html.contains("<!DOCTYPE html>"));
        assert!(html.contains("test-project"));
        assert!(html.contains("项目概览"));
        assert!(html.contains("架构分层"));
        assert!(html.contains("文件清单"));
    }

    #[test]
    fn test_to_markdown_contains_sections() {
        let graph = make_test_graph();
        let md = to_markdown(&graph);
        assert!(md.contains("# test-project"));
        assert!(md.contains("## 项目概览"));
        assert!(md.contains("## 架构分层"));
        assert!(md.contains("## 文件清单"));
        assert!(md.contains("## 导入关系"));
        assert!(md.contains("## 目录结构"));
        assert!(md.contains("## 引导之旅"));
        // Tables
        assert!(md.contains("| 属性 | 值 |"));
        assert!(md.contains("| 路径 | 语言 | 行数 | 类别 |"));
    }

    #[test]
    fn test_extract_line_count() {
        assert_eq!(extract_line_count("rust (150 lines)"), Some("150"));
        assert_eq!(
            extract_line_count("rust (150 lines, 2 definitions, 1 imports)"),
            Some("150")
        );
        assert_eq!(extract_line_count("no parens"), None);
    }

    #[test]
    fn test_html_escapes_angle_brackets() {
        let mut graph = make_test_graph();
        graph.project.name = "test <script>alert(1)</script>".into();
        let html = to_html(&graph);
        assert!(!html.contains("<script>alert"));
        assert!(html.contains("&lt;script&gt;"));

        let html_static = to_html_static(&graph);
        assert!(!html_static.contains("<script>alert"));
        assert!(html_static.contains("&lt;script&gt;"));
    }

    #[test]
    fn test_empty_graph() {
        let graph = KnowledgeGraph {
            version: "1.0.0".into(),
            kind: None,
            project: ProjectMeta {
                name: "empty".into(),
                languages: vec![],
                frameworks: vec![],
                description: "Empty project".into(),
                analyzed_at: "now".into(),
                git_commit_hash: "unknown".into(),
            },
            nodes: vec![],
            edges: vec![],
            layers: vec![],
            tour: vec![],
        };
        let html = to_html(&graph);
        assert!(html.contains("empty"));
        let html_static = to_html_static(&graph);
        assert!(html_static.contains("empty"));
        let md = to_markdown(&graph);
        assert!(md.contains("# empty"));
    }
}
